### PR TITLE
fix(build): Fail build on Firestore get failure

### LINKED ISSUE #87: Make build fail if Firestore fails
See attached logs.  If Firestore doesn't respond we can end up deploying a pretty much empty site.
[log-9a6939ef-6a83-43fd-a563-d4cf0c05b526.txt](https://github.com/firebase/firebaseopensource.com/files/2593169/log-9a6939ef-6a83-43fd-a563-d4cf0c05b526.txt)

```
Step #1: > firebaseopensource@1.0.0 get-routes /firebaseopensource.com/frontend
Step #1: > ts-node -O '{"module": "commonjs"}' src/scripts/routesList.ts
Step #1: 
Step #1: (node:113) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Step #1: [2018-11-16T01:09:37.877Z] @firebase/firestore: Firestore (5.0.4): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
Step #1: This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
Step #1: Found 7 routes
Step #1: Done.
Step #1: 
Step #1: > firebaseopensource@1.0.0 gen /firebaseopensource.com/frontend
Step #1: > nuxt generate
Step #1: 
Step #1: 2018-11-16T01:09:39.548Z nuxt:generate Generating...
Step #1: 2018-11-16T01:09:39.641Z nuxt:build App root: /firebaseopensource.com/frontend
Step #1: 2018-11-16T01:09:39.642Z nuxt:build Generating /firebaseopensource.com/frontend/.nuxt files...
Step #1: 2018-11-16T01:09:39.645Z nuxt:build Generating files...
Step #1: 2018-11-16T01:09:39.646Z nuxt:build Generating routes...
Step #1: 2018-11-16T01:09:39.687Z nuxt:build Building files...
Step #1: ts-loader: Using typescript@2.7.2 and /firebaseopensource.com/frontend/tsconfig.json
Step #1: WARNING Compiled with 1 warnings01:10:24
Step #1: 
Step #1: warning 
Step #1: 
Step #1: asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
Step #1: This can impact web performance.
Step #1: Assets: 
Step #1: pages/projects/_org/_repo/index.6e896a0c0fb4d8fb9b0f.js (431 kB)
Step #1: pages/platform/_platform/index.cff62769ba4c5316ae45.js (382 kB)
Step #1: pages/index.8d947a4d7f450037e236.js (382 kB)
Step #1: 
Step #1: Hash: f8bca12b158d16429f51
Step #1: Version: webpack 3.12.0
Step #1: Time: 43590ms
Step #1: Asset Size Chunks Chunk Names
Step #1: pages/projects/_org/_repo/index.6e896a0c0fb4d8fb9b0f.js 431 kB 0 [emitted] [big] pages/projects/_org/_repo/index
Step #1: pages/platform/_platform/index.cff62769ba4c5316ae45.js 382 kB 1 [emitted] [big] pages/platform/_platform/index
Step #1: pages/index.8d947a4d7f450037e236.js 382 kB 2 [emitted] [big] pages/index
Step #1: layouts/default.0a9ea840477ea6c560c6.js 400 bytes 3 [emitted] layouts/default
Step #1: vendor.f9914d07c40f138de8ae.js 144 kB 4 [emitted] vendor
Step #1: app.85e566f9c630006ee470.js 27.5 kB 5 [emitted] app
Step #1: manifest.f8bca12b158d16429f51.js 1.59 kB 6 [emitted] manifest
Step #1: LICENSES 5.68 kB [emitted] 
Step #1: + 3 hidden assets
Step #1: 
Step #1: WARNING in asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
Step #1: This can impact web performance.
Step #1: Assets: 
Step #1: pages/projects/_org/_repo/index.6e896a0c0fb4d8fb9b0f.js (431 kB)
Step #1: pages/platform/_platform/index.cff62769ba4c5316ae45.js (382 kB)
Step #1: pages/index.8d947a4d7f450037e236.js (382 kB)
Step #1: ts-loader: Using typescript@2.7.2 and /firebaseopensource.com/frontend/tsconfig.json
Step #1: Hash: aed0a0b54593fc64d618
Step #1: Version: webpack 3.12.0
Step #1: Time: 3995ms
Step #1: Asset Size Chunks Chunk Names
Step #1: server-bundle.json 251 kB [emitted] 
Step #1: 2018-11-16T01:10:28.330Z nuxt: Call generate:distRemoved hooks (1)
Step #1: 2018-11-16T01:10:28.331Z nuxt:generate Destination folder cleaned
Step #1: 2018-11-16T01:10:28.341Z nuxt: Call generate:distCopied hooks (1)
Step #1: 2018-11-16T01:10:28.341Z nuxt:generate Static & build files copied
Step #1: 2018-11-16T01:10:28.345Z nuxt:render Rendering url /
Step #1: 2018-11-16T01:10:28.377Z nuxt:render Rendering url platform/all
Step #1: 2018-11-16T01:10:28.380Z nuxt:render Rendering url platform/ios
Step #1: 2018-11-16T01:10:28.381Z nuxt:render Rendering url platform/android
Step #1: 2018-11-16T01:10:28.382Z nuxt:render Rendering url platform/web
Step #1: 2018-11-16T01:10:28.382Z nuxt:render Rendering url platform/games
Step #1: 2018-11-16T01:10:28.383Z nuxt:render Rendering url platform/admin
Step #1: index:asyncData(/)
Step #1: platform:asyncData(/platform/all)
Step #1: platform:asyncData(/platform/ios)
Step #1: platform:asyncData(/platform/android)
Step #1: platform:asyncData(/platform/web)
Step #1: platform:asyncData(/platform/games)
Step #1: platform:asyncData(/platform/admin)
Step #1: (node:137) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Step #1: [2018-11-16T01:10:38.672Z] @firebase/firestore: Firestore (5.0.4): Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds.
Step #1: This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
Step #1: 2018-11-16T01:10:39.051Z nuxt: Call generate:page hooks (1)
Step #1: 2018-11-16T01:10:39.188Z nuxt: Call generate:page hooks (1)
Step #1: 2018-11-16T01:10:39.267Z nuxt: Call generate:page hooks (1)
Step #1: 2018-11-16T01:10:39.336Z nuxt: Call generate:page hooks (1)
Step #1: 2018-11-16T01:10:39.381Z nuxt: Call generate:page hooks (1)
Step #1: 2018-11-16T01:10:39.451Z nuxt: Call generate:page hooks (1)
Step #1: 2018-11-16T01:10:39.521Z nuxt: Call generate:page hooks (1)
Step #1: 2018-11-16T01:10:39.521Z nuxt:generate Generate file: /index.html
Step #1: 2018-11-16T01:10:39.522Z nuxt:generate Generate file: platform/all/index.html
Step #1: 2018-11-16T01:10:39.522Z nuxt:generate Generate file: platform/ios/index.html
Step #1: 2018-11-16T01:10:39.523Z nuxt:generate Generate file: platform/android/index.html
Step #1: 2018-11-16T01:10:39.523Z nuxt:generate Generate file: platform/web/index.html
Step #1: 2018-11-16T01:10:39.523Z nuxt:generate Generate file: platform/games/index.html
Step #1: 2018-11-16T01:10:39.524Z nuxt:generate Generate file: platform/admin/index.html
Step #1: 2018-11-16T01:10:39.833Z nuxt:render Rendering url /
Step #1: 2018-11-16T01:10:39.835Z nuxt: Call generate:done hooks (1)
Step #1: 2018-11-16T01:10:39.836Z nuxt:generate HTML Files generated in 60.3s
Step #1: 2018-11-16T01:10:39.837Z nuxt:generate Generate done
Step #1: /firebaseopensource.com
Step #1: 
Step #1: === Deploying to 'fir-oss'...
Step #1: 
Step #1: i deploying hosting
Step #1: i hosting[fir-oss]: beginning deploy...
Step #1: i hosting[fir-oss]: found 24 files in frontend/dist
Step #1: ✔ hosting[fir-oss]: file upload complete
Step #1: i hosting[fir-oss]: finalizing version...
Step #1: ✔ hosting[fir-oss]: version finalized
Step #1: i hosting[fir-oss]: releasing new version...
Step #1: ✔ hosting[fir-oss]: release complete
Step #1: 
Step #1: ✔ Deploy complete!
```

### PR DESCRIPTION
**Pull request by anishkny**
Fixes #87.

Something like this? (TS noob, just trying to learn here 😄)

### CODE REVIEW

**Comment by samtstern** [comment]
@anishkny this will add nicer messages but won't actually fix the bug, since the whole deploy will still continue.

**Comment by anishkny** [comment]
Oh? Heres what I traced:

```
./build.sh
...
make build-hosting
...
npm run get-routes
...
ts-node -O '{\"module\": \"commonjs\"}' src/scripts/routesList.ts
...
RoutesList.getAll()
  .then(...)
  .catch(error => {
    console.error("Error getting list of routes", error);
    throw error;     // <---- BOOM!
  });
```

I thought the above would halt dead the `make` process with a non-zero exitcode?

**Comment by samtstern** [comment]
Adding a `throw` inside a `catch` is the same as not having a `catch` at all, it just makes the promise fail.

**Comment by anishkny** [comment]
Oh duh! Well one thing I can think of is something like:

```
process.on('unhandledRejection', error => {
  console.log('unhandledRejection', error.message);
  throw error;
});
```

**Comment by lupas** [comment]
@samtstern 
I think this can be closed, `routesList.ts` does not exist anymore since https://github.com/firebase/firebaseopensource.com/pull/151.

`getRoutes.ts` now gets all routes during build for sitemap and the generation of the pages, and if the Firestore call in getRoutes.ts fails, the **build fails**, too.

**Comment by lupas** [comment]
@samtstern 
I think this can be closed, see my comment here: https://github.com/firebase/firebaseopensource.com/pull/115#issuecomment-600178666

**Comment by samtstern** [comment]
@lupas thank you!  And thanks @anishkny for the initial work.

**Comment by lupas** [comment]
> @samtstern
> I think this can be closed, see my comment here: [#115 (comment)](https://github.com/firebase/firebaseopensource.com/pull/115#issuecomment-600178666)

Oops I actually wanted to post this second message on the issue itself here https://github.com/firebase/firebaseopensource.com/issues/87 , haha.

**Pull request closed without merging**
