### PR TITLE
Add jsayol/FireSQL

### PR DESCRIPTION
**Pull request by jsayol**
https://github.com/jsayol/FireSQL

### CODE REVIEW

**Comment by samtstern** [comment]
@jsayol nice!  Thanks for sending this over.

**Comment by samtstern** [comment]
Unless something is broken this will be picked up and published within 30 minutes

**Comment by jsayol** [comment]
Thanks Sam! I guess something must be broken, since it's been several hours and it's still not showing up. Please let me know if there's anything I can fix on my side :)

**Comment by jsayol** [comment]
Ahh, found the issue. I just checked and it looks like there's several other projects in the same situation, where they're in the database but don't show up in their categories.

The problem is that they don't have a `description` field, and the data is retrieved from `configs` [ordered by `description`](https://github.com/firebase/firebaseopensource.com/blob/1cd8f993537b6604593f1847a4bcfab718305ea2/frontend/src/components/Homepage/index.ts#L131).

That's very odd though. AFAIK doing an `.orderBy()` is not supposed to limit the results, and there's certainly nothing about it in the docs. Should I open a support ticket about this or is it a known issue?

You can see the difference between these 2 queries:
```js
db.collection("configs").where("platforms.web", "==", true).orderBy("name"); // 17 docs
db.collection("configs").where("platforms.web", "==", true).orderBy("description"); // 13 docs
```

**Comment by samtstern** [comment]
@jsayol there was also something broken on our side!

Should be working now:
https://firebaseopensource.com/projects/jsayol/firesql/

Thanks for contributing!

**Comment by samtstern** [comment]
Oh and the `orderBy('description')` thing is working as intended.  In Firestore `orderBy` is also an implicit existence filter, and we didn't want anything without a description showing up on the main page since it wouldn't look good.

But that's a good thing to look out for in the future!

**Pull request merged**
