### PR TITLE
Rebuild frontend (lupas)

### PR DESCRIPTION
**Pull request by samtstern**
cc @lupas

### CODE REVIEW

**Comment by samtstern** [comment]
@lupas I am using this PR to view the diff.  Would love if you could provide a basic "reviewers guide" so I know where I should focus my attention and what you have left to do.

**Comment by lupas** [comment]
@googlebot I consent.

**Comment by lupas** [comment]
@samtstern 

Struggling mostly with nuxt-typescript, first time using it thoroughly and it is less fun than I thought it would be 😝 I heard tho it's supposed to be a pain with Vue still, Vue 3 with the composition API is supposed to make it easier later this year.

Since it took me a while to get to a running version again after updating all NPM versions, the first commit is a bit big, so a lot of the changes are not reflected in the commit log.

**Key Changes:**

0. Updated all NPM dependencies
1. Using the Nuxt ["Error" Layout](https://nuxtjs.org/guide/views/#error-page) for the "four-oh-four" page
2. Moved all basic head() -> meta properties to the default layout (so we don't have to repeat on every page except if we want to overwrite it)
3. Use [asyncData](https://nuxtjs.org/api/#the-asyncdata-method) to load all relevant data from Firestore on each page before render
4. Pretty much rewrote how the `context.params` are handled on the **project** page. Not perfect, but the url now doesn't contain the `.md` extension anymore and the slashes don't matter. Also the error page should now always properly render.
5. Moved all Firebase related code to `assets/firebaseUtils.ts`
6. Split up some components into sub-components (especially when in `v-for`), and moved the logic and styles into the subcomponents. Should be easier to manage.
7. Moved everything into Single File .vue components. You might not like that, but it has some advantages (e.g. linting) and the goal is to make the components so small that it actually feels comfortable to work with SFC.
8. Replaced all internal `<a>` links with `<nuxt-link >`. Now you'll see the loading bar that now appears and no page refresh at click on the links.
9. Added `@nuxt/firebase`module.
10. No more need for `selected` attribute directly on the props, is now handled within the component
11. No more need for routes.json, data for sitemap gets fetched in production during build

Then some small stuff, like "outbound" icons in the sidebar, added "_blank" targets to some links, and some more small changes.

**Left to do:**

- [ ] Fix all `TODO:`'s

- [ ] Get rid of the @ts-ignore above the `@Component` decorators
I get a `no overload matches this call` typescript error I struggle to get rid of

- [ ] Either abstain from using the `firewings` module (it's my own) or quickly build the typing for it
(I kinda like it because it makes the queries so much simpler, less boilerplate code)

- [ ] Add missing typings and replace `any` annotations

- [ ] Write some tests (again)

- [ ] Write logic for "featured" projects (at this point it got lost - but not sure if it's even needed?)

**Future improvements I can think of:**
- [ ] Further split up some components
- [ ] Further clean styles (I think there's a bunch of duplication)
- [ ] Move static assets from `static` to `assets` and require, so webpack will process them.
- [ ] Add Style Linter / Formatter
- [ ] Clean up Firestore data (e.g. remove `selected` attribute and so on)

I might have forgot something, but I think that's most of it.

Was good practice for me to learn Typescript :) Let me know if you think some stuff is solved in a bad way or you see code I wrote that is not how it should be - I'm no JS expert 😅

**Comment by lupas** [comment]
> Featured projects are anything that appears on the homepage. Without any logic it's just `WHERE platform = "Android" ORDER BY stars` but sometimes there are projects with a high number of stars that are known to be dead / in bad shape and we don't want to show them on the homepage.

Okay, understood.

So since we use the `blacklist == false` filter when getting the projects from Firestore (for each category) with a limit of 6, we don't need any additional code client-side.
```js
  const ref = fireStore.collection('configs').orderBy(`platforms.${category.platform}`)
    .where('blacklist', '==', false)
    .where('fork', '==', false)
    .orderBy('stars', 'desc')
    .orderBy('description')
    .limit(limit)
```

So this can be avoided:
```html
<div class="project" v-for="project in ($refs.header && $refs.header.subheader_tab_selection == 'all')? category.featured : category.projects">
```

```js
if (category.featured.length < 6) {
    category.featured.push(catProj);
}
```

Meaning the featured functionality is already working as expected.

> - [x] Write logic for "featured" projects (at this point it got lost - but not sure if it's even needed?)

**Comment by lupas** [comment]
So the code is doing exactly the same as before, with quite a bunch of clean-ups and up-to-date dependencies. Will be finishing up the following and then it would be good for review.

**Required ToDos:**

- [ ]  Get rid of `WARN  Cannot stringify arbitrary non-POJOs Timestamp (repeated 153 times)` (warning existed before)
- [ ] Get rid of the @ts-ignore above the @Component decorators
Without results in `no overload matches this call` typescript warning
- [ ] Fix breaking `this.projectConfig.last_fetched.toDate()`
- [ ] Add Tests

**Optional ToDos:**
- [ ] Cleanup CSS
- [ ] Move static assets from static to assets and require, so webpack will process them.

**Comment by lupas** [comment]
@samtstern 
All done. Have a look.

The code should be nuxt-conform now, using all the latest dependencies and some other before-mentioned improvements and cleanups.

Most importantly: Routes are directly generated on `nuxt generate` via requests to Firestore (see `'./assets/getRoutes'`), for pre-rendering the pages as well as creating the sitemap.xml.

So all that is left to do is to adjust your build process. Basically its the following:
- Run `nuxt generate`
- Deploy `/dist` folder to Firebase Hosting

Example here: [fir-opensource-rebuild.firebaseapp.com](https://fir-opensource-rebuild.firebaseapp.com/)

I didn't touch the cloud functions / build process, since I don't know exactly how/when you trigger the builds.
But in general it seems like a lot of the code in the Cloud Functions is now also redundant (e.g. sanitizing html/external links).

**Comment by samtstern** [comment]
@lupas thank you so much!  I will take a look at this soon and make sure I can still get it all working.

**Comment by lupas** [comment]
@samtstern Great :) Let me know if something is unclear, happy to elaborate.

**Comment by samtstern** [comment]
Ok at first glance almost everything looks good!  Just a few things I noticed:

  * If I go to this page (http://localhost:3000/projects/firebase/firebaseui-android) and click on this link (http://localhost:3000/projects/firebase/auth/readme.md) I get a 404 ... do I need to change the Cloud Functions code to fix how we ingest the projects?
  * In `frontend` I had to `npm install` two packages before I could get the site running ... did I do something wrong or should we add these?
    * `@nuxt/webpack` (as a dependency)
    * `typescript` (as a dev dependency)

**Comment by lupas** [comment]
@samtstern 

1. Oh, the links within the markdown content, right? I'll make sure .md will be routed correctly, I'll upload a fix soon.
2. Yep. Just added them. Had them globally installed so I didn't realize.

**Comment by lupas** [comment]
@samtstern 

Added a simple fix with https://github.com/firebase/firebaseopensource.com/pull/151/commits/eebbee58a5654c22d08f9b9b5e365bffc3a1d907:
```js
  get cleanContent () {
    // Removes .md ending of all links that end with .md">
    return this.section.content.replace(/.md">/g, '">')
  }
```

I don't see a big performance issue with this approach since the html content is not huge and we pre-render pages for first visit anyway, 

What do you think?

**Comment by samtstern** [comment]
@lupas the performance is fine with me, the links are still a little strange though.

So this page:
http://localhost:3000/projects/firebase/firebaseui-android

Has a link like this:
```
<a href="firestore/readme">FirebaseUI Firestore</a>
```

So when you click it you go to:
http://localhost:3000/projects/firebase/firestore/readme (404)

But where you want to go is this:
http://localhost:3000/projects/firebase/firebaseui-android/firestore/readme

I think this is because the home page path used to have the trailing slash:
https://firebaseopensource.com/projects/firebase/firebaseui-android/

So the relative link resolved differently.  I can change the content-saving script to clean this up (and drop the MD as well).

**Comment by lupas** [comment]
> So the relative link resolved differently. I can change the content-saving script to clean this up (and drop the MD as well).

This is trickier than I thought 😅.

I'm sure I can find a way around it in the frontend, but I agree, cleaning it up with the content-saving script would be best after all.

Should I roll this (https://github.com/firebase/firebaseopensource.com/pull/151#issuecomment-599534102) back?

**Comment by samtstern** [comment]
@lupas I think I have the solution here:
https://github.com/lupas/firebaseopensource.com/pull/1/files

**Comment by lupas** [comment]
@samtstern 
Merged it. I don't have the entire Docker/Emulator setup at my end, so couldn't test it completely, but looks like this will work. 👍

**Comment by samtstern** [comment]
@lupas any more concerns about this PR or think we should merge it and give it a try?

**Comment by lupas** [comment]
> @lupas any more concerns about this PR or think we should merge it and give it a try?

All I can't really say is whether the entire automated build (ie. generate) workflow is all setup for the updated version already, but for the frontend itself no more concern, let's give it a go :)

**Comment by samtstern** [comment]
Oh right yeah.  I'll get that set up, thanks for reminding me!

**Comment by samtstern** [comment]
@lupas merged and deployed.  I can't thank you enough for this, what a fantastic open source contribution! 

Hopefully one day we can meet up at an event somewhere.  I'll be relocating to the Google London office later this year.

**Comment by lupas** [comment]
@samtstern 
Thanks :) Glad it's appreciated. I wrote you on the community Slack, in case we'll be in London at the same time.

Cheers!

**Pull request merged**
