### PR TITLE
Use Nuxt full-static mode

### LINKED ISSUE #170: [Feature] Implement Nuxt' full-static mode
**What Happened?**
Nuxt 2.13.0 was released!
Read here: https://nuxtjs.org/blog/going-full-static

**What Did You Expect to Happen**
Fulls static mode will be available with Nuxt v2.13.0.

**Screenshot (If Applicable)**
Nope, but:

Nuxt just released 2.13.0 which now includes a full static mode, meaning:
-> No more additional external calls to Firestore on route changes.
-> blazing fast pre-rendered html without page-reloads

As you remember @samtstern, we changed all the `<nuxt-link/>`'s back to `<a/>` so we won't reload data from Firestore on each route change. With the new Nuxt version and full-static mode that won't happen anymore, see article linked above.

So this issue is here for your information about that, and at some point when we have some spare time we can implement that for that project:

- [ ] Implement full-static mode as described in the article
- [ ] Switch `<a/>` links back to `<nuxt-link/>`

best regards

### PR DESCRIPTION
**Pull request by samtstern**
Fixes #170 

See:
https://nuxtjs.org/blog/going-full-static

### CODE REVIEW

**Comment by samtstern** [comment]
@lupas what do you think?

**Comment by samtstern** [comment]
Wow in some local testing this is *stupid fast* :-)

**Comment by lupas** [comment]
> @lupas what do you think?
> Wow in some local testing this is stupid fast :-)

Looks good! Wooohooo, that is indeed blazing fast :O  Can't stop clicking around.. 

One thing: Do the icons render properly for you?
Locally mine won't show properly:
Screenshot 2020-06-18 at 23 00 03

**Comment by samtstern** [comment]
@lupas they do render for me but that's concerning.  Maybe it's the `&display=swap` I added to the fonts `link` tag?  Can you see if removing that fixes it for you?

**Comment by samtstern** [comment]
Also I want to declare right now that Lighthouse gives this site a 69 for performance which is 🐮 💩

**Comment by lupas** [comment]
> @lupas they do render for me but that's concerning. Maybe it's the `&display=swap` I added to the fonts `link` tag? Can you see if removing that fixes it for you?

That didn't change anything, BUT moving back to `link rel="stylesheet"` did make them appear again. 🥳 

> Also I want to declare right now that Lighthouse gives this site a 69 for performance which is 🐮 💩

Someone told me long ago: Never trust Google ! ;-)

**Comment by samtstern** [comment]
@lupas ok I'll move it back, preload is too fancy.  Any other changes before I merge?

**Comment by lupas** [comment]
> @lupas ok I'll move it back, preload is too fancy. Any other changes before I merge?

Not at this point. Merge ahead :)

**Pull request merged**
