### PR TITLE
add vscode firebase-firestore-snippets

### PR DESCRIPTION
**Pull request by PeterHdd**

### CODE REVIEW

**Comment by samtstern** [comment]
LGTM thanks for your contribution!  It should appear on the site tomorrow. 

Also how did you hear about firebaseopensource.com ?

**Comment by PeterHdd** [comment]
Alright, no problem! I saw the website on twitter

**Comment by samtstern** [comment]
Page is up!
https://firebaseopensource.com/projects/peterhdd/firebase-firestore-snippets/

**Comment by PeterHdd** [comment]
Yup I saw it! Thank you Sam!

**Pull request merged**
